/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      spacing: {
        "md": "20px",
        "xs": "4px",
        "base": "8px",
        "sm": "12px",
        "lg": "32px",
        "gutter": "16px",
        "container-padding": "24px",
        "xl": "48px"
      },
      fontFamily: {
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "label-sm": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-sm": ["Be Vietnam Pro", "sans-serif"],
        "label-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg-mobile": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "32px", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }]
      },
      colors: {
        primary: "rgb(var(--primary-rgb) / <alpha-value>)",
        "primary-low": "rgb(var(--primary-low-rgb) / <alpha-value>)",
        "primary-hover": "rgb(var(--primary-hover-rgb) / <alpha-value>)",
        "primary-container": "#00818f",
        orange: {
          DEFAULT: "rgb(var(--orange-rgb) / <alpha-value>)",
          100: "#ffedd5",
          700: "#c2410c",
        },
        grey: "rgb(var(--grey-rgb) / <alpha-value>)",
        "grey-low": "rgb(var(--grey-low-rgb) / <alpha-value>)",
        "text-high": "rgb(var(--text-high-rgb) / <alpha-value>)",
        border: "rgb(var(--border-rgb) / <alpha-value>)",
        surface: "#f8fafb",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3d494b",
        "surface-container": "#eceeef",
        "surface-container-low": "#f2f4f5",
        "surface-container-high": "#e6e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dadb",
        "surface-bright": "#f8fafb",
        "outline-variant": "#bcc9cb",
        outline: "#6d797c",
        tertiary: "#795600",
        "tertiary-container": "#986d00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#5e4200",
        "tertiary-fixed": "#ffdea8",
        "tertiary-fixed-dim": "#ffba20",
        secondary: "#006d37",
        "secondary-container": "#6bfe9c",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#00210c",
        "on-secondary-fixed-variant": "#005228",
        "on-secondary-container": "#00743a",
        "secondary-fixed": "#6bfe9c",
        "secondary-fixed-dim": "#4ae183",
        "surface-tint": "#006874",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#eff1f2",
        "inverse-primary": "#62d6e8",
        "primary-fixed": "#98f0ff",
        "primary-fixed-dim": "#62d6e8",
        "on-primary-fixed": "#001f24",
        "on-primary-fixed-variant": "#004f58",
        "on-primary-container": "#f7feff",
        "on-primary": "#ffffff",
        "on-background": "#191c1d",
      },
      animation: {
        "fade-up": "fadeUp 0.5s ease-out",
        "shift-gradient": "shiftGradient 6s ease-in-out infinite",
      },
      keyframes: {
        fadeUp: {
          from: { opacity: "0", transform: "translateY(12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        shiftGradient: {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
      },
      boxShadow: {
        card: "0 1px 3px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)",
        "card-hover": "0 4px 15px rgba(0, 0, 0, 0.06)",
        "primary-soft": "0 8px 25px rgba(0, 135, 154, 0.1)",
      },
    },
  },
  plugins: [],
};
