/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--primary-rgb) / <alpha-value>)",
        "primary-low": "rgb(var(--primary-low-rgb) / <alpha-value>)",
        "primary-hover": "rgb(var(--primary-hover-rgb) / <alpha-value>)",
        orange: {
          DEFAULT: "rgb(var(--orange-rgb) / <alpha-value>)",
          100: "#ffedd5",
          700: "#c2410c",
        },
        grey: "rgb(var(--grey-rgb) / <alpha-value>)",
        "grey-low": "rgb(var(--grey-low-rgb) / <alpha-value>)",
        "text-high": "rgb(var(--text-high-rgb) / <alpha-value>)",
        border: "rgb(var(--border-rgb) / <alpha-value>)",
        surface: "#f8fafb",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3e4949",
        "surface-container": "#eceeef",
        "surface-container-low": "#f2f4f5",
        "surface-container-high": "#e6e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d8dadb",
        "surface-bright": "#f8fafb",
        "outline-variant": "#bdc9c9",
        outline: "#6e797a",
        tertiary: "#426363",
        "tertiary-container": "#5b7c7c",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "on-tertiary-fixed": "#002020",
        "on-tertiary-fixed-variant": "#2b4c4c",
        "tertiary-fixed": "#c6e9e9",
        "tertiary-fixed-dim": "#aacdcd",
        secondary: "#8a5100",
        "secondary-container": "#fd9d27",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#2c1600",
        "on-secondary-fixed-variant": "#693c00",
        "on-secondary-container": "#673b00",
        "secondary-fixed": "#ffdcbe",
        "secondary-fixed-dim": "#ffb86f",
        "surface-tint": "#00696d",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#eff1f2",
        "inverse-primary": "#77d5da",
        "primary-fixed": "#94f2f7",
        "primary-fixed-dim": "#77d5da",
        "on-primary-fixed": "#002021",
        "on-primary-fixed-variant": "#004f52",
        "on-primary-container": "#ffffff",
        "on-primary": "#ffffff",
        "on-background": "#191c1d",
      },
      animation: {
        "fade-up": "fadeUp 0.5s ease-out",
        "shift-gradient": "shiftGradient 6s ease-in-out infinite",
      },
      keyframes: {
        fadeUp: {
          from: { opacity: "0", transform: "translateY(12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        shiftGradient: {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
      },
      boxShadow: {
        card: "0 1px 3px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)",
        "card-hover": "0 4px 15px rgba(0, 0, 0, 0.06)",
        "primary-soft": "0 8px 25px rgba(0, 135, 154, 0.1)",
      },
    },
  },
  plugins: [],
};
