const routes = {
  home: "/",
  login: "/login",
  register: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  about: "/about",
  dictionary: "/dictionary",
  notebook: "/dictionary/notebook",
  notebookDetail: "/dictionary/notebook/:notebookId",
  flashcards: "/dictionary/notebook/:notebookId/flashcards",
  flashcardsLegacy: "/dictionary/notebook/flashcards",
  practice: "/practice",
  level: "/practice/:level",
  test: "/practice/:level/test/:testId",
  results: "/practice/:level/results/:testId",
  resultDetail: "/practice/:level/results/detail/:testId",
  conversationPractice: "/conversation",
  chatAI: "/chat-ai",
  community: "/community",
  postDetail: "/community/:id",
  newPost: "/community/new",
  dashboard: "/dashboard",
  onboarding: "/onboarding",
  learningPathProgress: "/dashboard/learning-path",
  achievements: "/dashboard/achievements",
  goals: "/dashboard/goals",
  setting: "/profile",
  settingLegacy: "/dashboard/settings",
  kanjiLookup: "/kanji",
  jlpt: "/jlpt",
  reading: "/reading",
  jlptFlashcard: "jlpt/flashcards",
  admin: "/admin",
  user: "/admin/users",
  dictionaryAdmin: "/admin/dictionary",
  dictionaryAdminAdd: "/admin/dictionary/:resource/add",
  dictionaryAdminUpdate: "/admin/dictionary/:resource/update/:id",
  adminTest: "/admin/tests",
  createTest: "/admin/tests/create",
  adminTestStatistics: "/admin/tests/statistics/:examId",
  updateTest: "/admin/tests/update/:id",
  adminPosts: "/admin/posts",
  adminViolations: "/admin/violations",
  adminTransactions: "/admin/transactions",
  adminReading: "/admin/reading",
  adminConversation: "/admin/conversation",
  adminLearningPaths: "/admin/learning-paths",
  adminLearningPathPlacementNew: "/admin/learning-paths/placement/new",
  adminLearningPathPlacementEdit: "/admin/learning-paths/placement/:questionId/edit",
  adminLearningPathDetail: "/admin/learning-paths/:id",
  translate: "/translate"
  ,
  payment: "/payment"
  ,
  paymentCheckout: "/payment/checkout"
};

export default routes;
